// GENERATED by scripts/build-registry.ts — do not edit manually

import type { Timeline } from "../schema/timeline";

import tl_0 from "../../../examples/demo-timeline.json";
import tl_1 from "../../../examples/nextjs-app-router-reel.json";
import tl_2 from "../../../examples/syntra/week-01-mar-09-three-failures-of-enterprise-ai---youtube-shorts.json";
import tl_3 from "../../../examples/syntra/week-01-mar-09-what-is-an-intelligence-layer---youtube-shorts.json";
import tl_4 from "../../../examples/syntra/week-01-mar-09-why-ai-tools-don't-talk---youtube-shorts.json";
import tl_5 from "../../../examples/syntra/week-02-mar-16-agent-hq-launch---youtube-shorts.json";
import tl_6 from "../../../examples/syntra/week-02-mar-16-introducing-syntra---full-company-video.json";
import tl_7 from "../../../examples/syntra/week-02-mar-16-introducing-syntra---youtube-shorts.json";
import tl_8 from "../../../examples/syntra/week-02-mar-16-islas-launch---youtube-shorts.json";
import tl_9 from "../../../examples/syntra/week-03-mar-23-model-agnostic-architecture---youtube-shorts.json";
import tl_10 from "../../../examples/syntra/week-03-mar-23-platform-vs-intelligence-layer---youtube-shorts.json";
import tl_11 from "../../../examples/syntra/week-03-mar-23-why-we-built-syntra---youtube-shorts.json";
import tl_12 from "../../../examples/syntra/week-04-mar-30-5-layer-intelligence-architecture---youtube-shorts.json";
import tl_13 from "../../../examples/syntra/week-04-mar-30-data-sovereignty-for-africa---youtube-shorts.json";
import tl_14 from "../../../examples/syntra/week-04-mar-30-persistent-memory---youtube-shorts.json";
import tl_15 from "../../../examples/syntra/week-05-apr-06-building-ai-that-compounds-intelligence-over-time.json";
import tl_16 from "../../../examples/syntra/week-05-apr-06-compounding-intelligence:-ai-systems-that-learn.json";
import tl_17 from "../../../examples/syntra/week-05-apr-06-compounding-intelligence:-ai-that-learns.json";
import tl_18 from "../../../examples/syntra/week-05-apr-06-context-engineering:-same-model,-different-results.json";
import tl_19 from "../../../examples/syntra/week-05-apr-06-context-engineering:-the-new-frontier-of-ai.json";
import tl_20 from "../../../examples/syntra/week-05-apr-06-multi-agent-orchestration-problems-&-fixes.json";
import tl_21 from "../../../examples/syntra/week-05-apr-06-multi-agent-orchestration:-4-problems-&-solutions.json";
import tl_22 from "../../../examples/syntra/week-05-apr-06-multi-agent-orchestration:-a-practical-guide.json";
import tl_23 from "../../../examples/syntra/week-06-apr-13-intelligent-forgetting-in-ai-memory-systems.json";
import tl_24 from "../../../examples/syntra/week-06-apr-13-the-role-of-forgetting-in-ai-memory-systems.json";
import tl_25 from "../../../examples/syntra/week-07-apr-20-ai-strategy-east-africa---full-video.json";
import tl_26 from "../../../examples/syntra/week-07-apr-20-ai-strategy-east-africa---tiktok.json";
import tl_27 from "../../../examples/syntra/week-07-apr-20-ai-strategy-east-africa---youtube-short.json";
import tl_28 from "../../../examples/syntra/week-07-apr-20-knowledge-graphs---full-video.json";
import tl_29 from "../../../examples/syntra/week-07-apr-20-knowledge-graphs---tiktok.json";
import tl_30 from "../../../examples/syntra/week-07-apr-20-knowledge-graphs---youtube-short.json";
import tl_31 from "../../../examples/syntra/week-07-apr-20-local-first-ai---full-video.json";
import tl_32 from "../../../examples/syntra/week-07-apr-20-local-first-ai---tiktok.json";
import tl_33 from "../../../examples/syntra/week-07-apr-20-local-first-ai---youtube-short.json";
import tl_34 from "../../../examples/syntra/week-08-apr-27-future-of-work---full-video.json";
import tl_35 from "../../../examples/syntra/week-08-apr-27-future-of-work---tiktok.json";
import tl_36 from "../../../examples/syntra/week-08-apr-27-future-of-work---youtube-short.json";
import tl_37 from "../../../examples/syntra/week-08-apr-27-generative-ui---full-video.json";
import tl_38 from "../../../examples/syntra/week-08-apr-27-generative-ui---tiktok.json";
import tl_39 from "../../../examples/syntra/week-08-apr-27-generative-ui---youtube-short.json";
import tl_40 from "../../../examples/syntra/week-08-apr-27-token-budgets---full-video.json";
import tl_41 from "../../../examples/syntra/week-08-apr-27-token-budgets---tiktok.json";
import tl_42 from "../../../examples/syntra/week-08-apr-27-token-budgets---youtube-short.json";
import tl_43 from "../../../examples/syntra/week-09-may-04-ai-competitive-moat---full-video.json";
import tl_44 from "../../../examples/syntra/week-09-may-04-ai-competitive-moat---tiktok.json";
import tl_45 from "../../../examples/syntra/week-09-may-04-ai-competitive-moat---youtube-short.json";
import tl_46 from "../../../examples/syntra/week-09-may-04-ai-financial-services-architecture---full-video.json";
import tl_47 from "../../../examples/syntra/week-09-may-04-ai-in-financial-services---tiktok.json";
import tl_48 from "../../../examples/syntra/week-09-may-04-ai-in-financial-services---youtube-short.json";
import tl_49 from "../../../examples/syntra/week-09-may-04-intelligence-layer-assessment---full-video.json";
import tl_50 from "../../../examples/syntra/week-09-may-04-intelligence-layer-assessment---youtube-short.json";
import tl_51 from "../../../examples/syntra/week-09-may-04-why-your-ai-initiative-stalled.json";
import tl_52 from "../../../examples/syntra/week-10-may-11-100+-model-support---full-video.json";
import tl_53 from "../../../examples/syntra/week-10-may-11-100+-model-support---tiktok.json";
import tl_54 from "../../../examples/syntra/week-10-may-11-100+-model-support---youtube-short.json";
import tl_55 from "../../../examples/syntra/week-10-may-11-agent-augmented-organizations---full-video.json";
import tl_56 from "../../../examples/syntra/week-10-may-11-agent-augmented-organizations---tiktok.json";
import tl_57 from "../../../examples/syntra/week-10-may-11-agent-augmented-organizations---youtube-short.json";
import tl_58 from "../../../examples/syntra/week-10-may-11-department-aware-ai---full-video.json";
import tl_59 from "../../../examples/syntra/week-10-may-11-department-aware-ai---tiktok.json";
import tl_60 from "../../../examples/syntra/week-10-may-11-department-aware-ai---youtube-short.json";
import tl_61 from "../../../examples/syntra/week-11-may-18-air-gapped-ai---full-video.json";
import tl_62 from "../../../examples/syntra/week-11-may-18-air-gapped-ai---tiktok.json";
import tl_63 from "../../../examples/syntra/week-11-may-18-air-gapped-ai---youtube-short.json";
import tl_64 from "../../../examples/syntra/week-11-may-18-consulting-approach---full-video.json";
import tl_65 from "../../../examples/syntra/week-11-may-18-consulting-approach---youtube-short.json";
import tl_66 from "../../../examples/syntra/week-11-may-18-consulting-approach-to-ai---tiktok.json";
import tl_67 from "../../../examples/syntra/week-11-may-18-private-ai---full-video.json";
import tl_68 from "../../../examples/syntra/week-11-may-18-private-ai---tiktok.json";
import tl_69 from "../../../examples/syntra/week-11-may-18-private-ai---youtube-short.json";
import tl_70 from "../../../examples/syntra/week-12-may-25-how-we-use-our-products---full-video.json";
import tl_71 from "../../../examples/syntra/week-12-may-25-how-we-use-our-products---tiktok.json";
import tl_72 from "../../../examples/syntra/week-12-may-25-how-we-use-our-products---youtube-short.json";
import tl_73 from "../../../examples/syntra/week-12-may-25-measuring-ai-roi---full-video.json";
import tl_74 from "../../../examples/syntra/week-12-may-25-measuring-ai-roi---tiktok.json";
import tl_75 from "../../../examples/syntra/week-12-may-25-measuring-ai-roi---youtube-short.json";
import tl_76 from "../../../examples/syntra/week-12-may-25-next-era---full-video.json";
import tl_77 from "../../../examples/syntra/week-12-may-25-next-era---youtube-short.json";
import tl_78 from "../../../examples/syntra/week-12-may-25-next-era-of-institutional-intelligence---tiktok.json";

export const COMPOSITIONS: readonly { id: string; timeline: Timeline }[] = [
  { id: "ai-quarterly-review", timeline: tl_0 as unknown as Timeline },
  { id: "nextjs-app-router-reel", timeline: tl_1 as unknown as Timeline },
  { id: "week-01-mar-09-three-failures-of-enterprise-ai---youtube-shorts", timeline: tl_2 as unknown as Timeline },
  { id: "week-01-mar-09-what-is-an-intelligence-layer---youtube-shorts", timeline: tl_3 as unknown as Timeline },
  { id: "week-01-mar-09-why-ai-tools-don-t-talk---youtube-shorts", timeline: tl_4 as unknown as Timeline },
  { id: "week-02-mar-16-agent-hq-launch---youtube-shorts", timeline: tl_5 as unknown as Timeline },
  { id: "week-02-mar-16-introducing-syntra---full-company-video", timeline: tl_6 as unknown as Timeline },
  { id: "week-02-mar-16-introducing-syntra---youtube-shorts", timeline: tl_7 as unknown as Timeline },
  { id: "week-02-mar-16-islas-launch---youtube-shorts", timeline: tl_8 as unknown as Timeline },
  { id: "week-03-mar-23-model-agnostic-architecture---youtube-shorts", timeline: tl_9 as unknown as Timeline },
  { id: "week-03-mar-23-platform-vs-intelligence-layer---youtube-shorts", timeline: tl_10 as unknown as Timeline },
  { id: "week-03-mar-23-why-we-built-syntra---youtube-shorts", timeline: tl_11 as unknown as Timeline },
  { id: "week-04-mar-30-5-layer-intelligence-architecture---youtube-shorts", timeline: tl_12 as unknown as Timeline },
  { id: "week-04-mar-30-data-sovereignty-for-africa---youtube-shorts", timeline: tl_13 as unknown as Timeline },
  { id: "week-04-mar-30-persistent-memory---youtube-shorts", timeline: tl_14 as unknown as Timeline },
  { id: "week-05-apr-06-building-ai-that-compounds-intelligence-over-time", timeline: tl_15 as unknown as Timeline },
  { id: "week-05-apr-06-compounding-intelligence--ai-systems-that-learn", timeline: tl_16 as unknown as Timeline },
  { id: "week-05-apr-06-compounding-intelligence--ai-that-learns", timeline: tl_17 as unknown as Timeline },
  { id: "week-05-apr-06-context-engineering--same-model--different-results", timeline: tl_18 as unknown as Timeline },
  { id: "week-05-apr-06-context-engineering--the-new-frontier-of-ai", timeline: tl_19 as unknown as Timeline },
  { id: "week-05-apr-06-multi-agent-orchestration-problems---fixes", timeline: tl_20 as unknown as Timeline },
  { id: "week-05-apr-06-multi-agent-orchestration--4-problems---solutions", timeline: tl_21 as unknown as Timeline },
  { id: "week-05-apr-06-multi-agent-orchestration--a-practical-guide", timeline: tl_22 as unknown as Timeline },
  { id: "week-06-apr-13-intelligent-forgetting-in-ai-memory-systems", timeline: tl_23 as unknown as Timeline },
  { id: "week-06-apr-13-the-role-of-forgetting-in-ai-memory-systems", timeline: tl_24 as unknown as Timeline },
  { id: "week-07-apr-20-ai-strategy-east-africa---full-video", timeline: tl_25 as unknown as Timeline },
  { id: "week-07-apr-20-ai-strategy-east-africa---tiktok", timeline: tl_26 as unknown as Timeline },
  { id: "week-07-apr-20-ai-strategy-east-africa---youtube-short", timeline: tl_27 as unknown as Timeline },
  { id: "week-07-apr-20-knowledge-graphs---full-video", timeline: tl_28 as unknown as Timeline },
  { id: "week-07-apr-20-knowledge-graphs---tiktok", timeline: tl_29 as unknown as Timeline },
  { id: "week-07-apr-20-knowledge-graphs---youtube-short", timeline: tl_30 as unknown as Timeline },
  { id: "week-07-apr-20-local-first-ai---full-video", timeline: tl_31 as unknown as Timeline },
  { id: "week-07-apr-20-local-first-ai---tiktok", timeline: tl_32 as unknown as Timeline },
  { id: "week-07-apr-20-local-first-ai---youtube-short", timeline: tl_33 as unknown as Timeline },
  { id: "week-08-apr-27-future-of-work---full-video", timeline: tl_34 as unknown as Timeline },
  { id: "week-08-apr-27-future-of-work---tiktok", timeline: tl_35 as unknown as Timeline },
  { id: "week-08-apr-27-future-of-work---youtube-short", timeline: tl_36 as unknown as Timeline },
  { id: "week-08-apr-27-generative-ui---full-video", timeline: tl_37 as unknown as Timeline },
  { id: "week-08-apr-27-generative-ui---tiktok", timeline: tl_38 as unknown as Timeline },
  { id: "week-08-apr-27-generative-ui---youtube-short", timeline: tl_39 as unknown as Timeline },
  { id: "week-08-apr-27-token-budgets---full-video", timeline: tl_40 as unknown as Timeline },
  { id: "week-08-apr-27-token-budgets---tiktok", timeline: tl_41 as unknown as Timeline },
  { id: "week-08-apr-27-token-budgets---youtube-short", timeline: tl_42 as unknown as Timeline },
  { id: "week-09-may-04-ai-competitive-moat---full-video", timeline: tl_43 as unknown as Timeline },
  { id: "week-09-may-04-ai-competitive-moat---tiktok", timeline: tl_44 as unknown as Timeline },
  { id: "week-09-may-04-ai-competitive-moat---youtube-short", timeline: tl_45 as unknown as Timeline },
  { id: "week-09-may-04-ai-financial-services-architecture---full-video", timeline: tl_46 as unknown as Timeline },
  { id: "week-09-may-04-ai-in-financial-services---tiktok", timeline: tl_47 as unknown as Timeline },
  { id: "week-09-may-04-ai-in-financial-services---youtube-short", timeline: tl_48 as unknown as Timeline },
  { id: "week-09-may-04-intelligence-layer-assessment---full-video", timeline: tl_49 as unknown as Timeline },
  { id: "week-09-may-04-intelligence-layer-assessment---youtube-short", timeline: tl_50 as unknown as Timeline },
  { id: "week-09-may-04-why-your-ai-initiative-stalled", timeline: tl_51 as unknown as Timeline },
  { id: "week-10-may-11-100--model-support---full-video", timeline: tl_52 as unknown as Timeline },
  { id: "week-10-may-11-100--model-support---tiktok", timeline: tl_53 as unknown as Timeline },
  { id: "week-10-may-11-100--model-support---youtube-short", timeline: tl_54 as unknown as Timeline },
  { id: "week-10-may-11-agent-augmented-organizations---full-video", timeline: tl_55 as unknown as Timeline },
  { id: "week-10-may-11-agent-augmented-organizations---tiktok", timeline: tl_56 as unknown as Timeline },
  { id: "week-10-may-11-agent-augmented-organizations---youtube-short", timeline: tl_57 as unknown as Timeline },
  { id: "week-10-may-11-department-aware-ai---full-video", timeline: tl_58 as unknown as Timeline },
  { id: "week-10-may-11-department-aware-ai---tiktok", timeline: tl_59 as unknown as Timeline },
  { id: "week-10-may-11-department-aware-ai---youtube-short", timeline: tl_60 as unknown as Timeline },
  { id: "week-11-may-18-air-gapped-ai---full-video", timeline: tl_61 as unknown as Timeline },
  { id: "week-11-may-18-air-gapped-ai---tiktok", timeline: tl_62 as unknown as Timeline },
  { id: "week-11-may-18-air-gapped-ai---youtube-short", timeline: tl_63 as unknown as Timeline },
  { id: "week-11-may-18-consulting-approach---full-video", timeline: tl_64 as unknown as Timeline },
  { id: "week-11-may-18-consulting-approach---youtube-short", timeline: tl_65 as unknown as Timeline },
  { id: "week-11-may-18-consulting-approach-to-ai---tiktok", timeline: tl_66 as unknown as Timeline },
  { id: "week-11-may-18-private-ai---full-video", timeline: tl_67 as unknown as Timeline },
  { id: "week-11-may-18-private-ai---tiktok", timeline: tl_68 as unknown as Timeline },
  { id: "week-11-may-18-private-ai---youtube-short", timeline: tl_69 as unknown as Timeline },
  { id: "week-12-may-25-how-we-use-our-products---full-video", timeline: tl_70 as unknown as Timeline },
  { id: "week-12-may-25-how-we-use-our-products---tiktok", timeline: tl_71 as unknown as Timeline },
  { id: "week-12-may-25-how-we-use-our-products---youtube-short", timeline: tl_72 as unknown as Timeline },
  { id: "week-12-may-25-measuring-ai-roi---full-video", timeline: tl_73 as unknown as Timeline },
  { id: "week-12-may-25-measuring-ai-roi---tiktok", timeline: tl_74 as unknown as Timeline },
  { id: "week-12-may-25-measuring-ai-roi---youtube-short", timeline: tl_75 as unknown as Timeline },
  { id: "week-12-may-25-next-era---full-video", timeline: tl_76 as unknown as Timeline },
  { id: "week-12-may-25-next-era---youtube-short", timeline: tl_77 as unknown as Timeline },
  { id: "week-12-may-25-next-era-of-institutional-intelligence---tiktok", timeline: tl_78 as unknown as Timeline }
];
