/**
 * Registry code-generator.
 * Run with: bun scripts/build-registry.ts
 *
 * Globs examples/**‌/*.json, validates each against TimelineSchema,
 * asserts unique IDs, then emits src/remotion/compositions/registry.generated.ts.
 */

import * as fs from "node:fs";
import * as path from "node:path";
import { TimelineSchema, type Timeline } from "../src/remotion/schema/timeline";

// ── 1. Find all JSON files under examples/ ───────────────────────────────────

const REPO_ROOT = path.resolve(import.meta.dir, "..");
const EXAMPLES_DIR = path.join(REPO_ROOT, "examples");
const OUT_FILE = path.join(
  REPO_ROOT,
  "src/remotion/compositions/registry.generated.ts"
);

function findJsonFiles(dir: string): string[] {
  const results: string[] = [];
  if (!fs.existsSync(dir)) return results;

  const entries = fs.readdirSync(dir, { withFileTypes: true });
  for (const entry of entries) {
    const fullPath = path.join(dir, entry.name);
    if (entry.isDirectory()) {
      results.push(...findJsonFiles(fullPath));
    } else if (entry.isFile() && entry.name.endsWith(".json")) {
      results.push(fullPath);
    }
  }
  return results;
}

const jsonFiles = findJsonFiles(EXAMPLES_DIR).sort(); // deterministic alphabetical order

if (jsonFiles.length === 0) {
  console.error("No JSON files found under examples/");
  process.exit(1);
}

console.log(`Found ${jsonFiles.length} JSON file(s) under examples/`);

// ── 2. Parse + validate each file ────────────────────────────────────────────

const ID_REGEX = /^[a-zA-Z0-9_-]+$/;

const entries: Array<{ relPath: string; id: string }> = [];
const seenIds = new Map<string, string>(); // id → file path

for (const filePath of jsonFiles) {
  const relPath = path.relative(REPO_ROOT, filePath);

  let raw: unknown;
  try {
    raw = JSON.parse(fs.readFileSync(filePath, "utf8"));
  } catch (err) {
    console.error(`\nFailed to parse JSON: ${relPath}`);
    console.error(err);
    process.exit(1);
  }

  const result = TimelineSchema.safeParse(raw);
  if (!result.success) {
    console.error(`\nSchema validation failed for: ${relPath}`);
    console.error(result.error.format());
    process.exit(1);
  }

  const timeline = result.data as Timeline;
  const id = timeline.id;

  // Validate ID format
  if (!ID_REGEX.test(id)) {
    console.error(
      `\nInvalid ID format in ${relPath}: "${id}"\n` +
        `IDs must match /^[a-zA-Z0-9_-]+$/`
    );
    process.exit(1);
  }

  // Check uniqueness
  if (seenIds.has(id)) {
    console.error(
      `\nDuplicate timeline ID "${id}" found in:\n` +
        `  ${seenIds.get(id)}\n` +
        `  ${relPath}`
    );
    process.exit(1);
  }

  seenIds.set(id, relPath);
  entries.push({ relPath, id });
}

console.log(`All ${entries.length} timelines validated successfully.`);

// ── 3. Emit registry.generated.ts ────────────────────────────────────────────

// The generated file lives at src/remotion/compositions/registry.generated.ts
// Relative path from there to repo root is ../../../
// So examples/syntra/foo.json → ../../../examples/syntra/foo.json

const GENERATED_BASE = path.join(REPO_ROOT, "src/remotion/compositions");

const lines: string[] = [];
lines.push(
  "// GENERATED by scripts/build-registry.ts — do not edit manually"
);
lines.push("");
lines.push(
  'import type { Timeline } from "../schema/timeline";'
);
lines.push("");

// Import lines
for (let i = 0; i < entries.length; i++) {
  const { relPath } = entries[i];
  // relPath is relative to repo root, e.g. "examples/syntra/foo.json"
  const importPath =
    path.relative(GENERATED_BASE, path.join(REPO_ROOT, relPath));
  // Normalise to forward slashes (Windows safety)
  const importPathNorm = importPath.split(path.sep).join("/");
  // Keep the .json extension — resolveJsonModule handles it and the explicit
  // extension is clearer for readers and bundler resolution.
  lines.push(`import tl_${i} from "${importPathNorm}";`);
}

lines.push("");
lines.push(
  "export const COMPOSITIONS: readonly { id: string; timeline: Timeline }[] = ["
);

for (let i = 0; i < entries.length; i++) {
  const { id } = entries[i];
  const comma = i < entries.length - 1 ? "," : "";
  // `as unknown as Timeline` is required because resolveJsonModule infers a
  // narrow literal type for the JSON, not the Zod-inferred Timeline type.
  // Runtime correctness is guaranteed by the safeParse validation above —
  // the TypeScript cast is a formality, not the actual safety check.
  lines.push(`  { id: "${id}", timeline: tl_${i} as unknown as Timeline }${comma}`);
}

lines.push("];");
lines.push(""); // trailing newline

const output = lines.join("\n");

fs.mkdirSync(path.dirname(OUT_FILE), { recursive: true });
fs.writeFileSync(OUT_FILE, output, "utf8");

console.log(`\nEmitted: ${path.relative(REPO_ROOT, OUT_FILE)}`);
console.log(`  ${entries.length} compositions registered.`);
